### ISSUE TITLE
Macros disappear when using add-a-request

### ISSUE THREAD

**Issue by ours-code** [pajswigger/add-request-to-macro#1] opened 2018-07-04 09:21 UTC
Hello,

When using add-a-request all my macros are removed. 
This is using Burp 1.7.34 (we downgraded because of the macro issue on 1.7.35), there are no stdout or stderr of the add-a-request extension.
Running on Windows server 2012.

Let me know if you need other details to reproduce.

Thanks,

![macrospresent](https://user-images.githubusercontent.com/3473632/42268626-4b97ee20-7f7c-11e8-815f-04fb04d6134c.png)
![add-request](https://user-images.githubusercontent.com/3473632/42268629-4bd10840-7f7c-11e8-98d1-43ee2a43cad6.png)
![nomoremacros](https://user-images.githubusercontent.com/3473632/42268627-4bb3dcd4-7f7c-11e8-8c38-1d744138aa6b.png)

**Comment by pajswigger** [comment] 2018-07-11 09:21
We've not been able to reproduce this. I suspect there is something specific about one of your macros that is causing a problem with the extension. If you are able to share, please save your macros (using the cog button) and send to support@portswigger.net We'll treat your data in confidence and delete once the issue is diagnosed.

**Comment by pajswigger** [comment] 2018-07-12 15:04
This was a Unicode encoding issue. Fixed by using a different JSON library.

**Closed as completed by pajswigger** 2018-07-12 15:04 UTC
